In [569]:
import numpy as np
import pandas as pd

np.set_printoptions(suppress=True,precision=2,linewidth=100)

In [570]:
run_data_np=np.genfromtxt("loan-data.csv",delimiter=";",autostrip=True ,skip_header=1)
run_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])


CHECKING FOR INCOMPLETE DATA

In [571]:
np.isnan(run_data_np).sum()

88005

In [572]:
temporary_fill=np.nanmax(run_data_np)+1
temporary_mean=np.nanmean(run_data_np,axis=0)
temporary_mean

<ipython-input-572-0c3ee3a9164d>:2: RuntimeWarning: Mean of empty slice
  temporary_mean=np.nanmean(run_data_np,axis=0)


array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])


SPLITTING DATA

In [573]:
column_string=np.argwhere(np.isnan(temporary_mean)).squeeze()
column_string

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [574]:
column_numeric=np.argwhere(np.isnan(temporary_mean)==False).squeeze()
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

REIMPORTING DATASET

In [575]:
loan_data_string=np.genfromtxt("loan-data.csv",delimiter=";",autostrip=True 
                               ,usecols=column_string, skip_header=1,dtype="str")
loan_data_string

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [576]:
header_full=np.genfromtxt("loan-data.csv",delimiter=";",autostrip=True 
                               , skip_footer=run_data_np.shape[0],dtype="str")
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [577]:
header_string,header_numeric=header_full[column_string],header_full[column_numeric]


In [578]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [579]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')


MANIPULATING STRING COLUMNS

In [580]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [581]:
header_string[0]="issue-date"

ISSUE DATE

In [582]:
np.unique(loan_data_string[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [583]:
loan_data_string[:,0]=np.chararray.strip(loan_data_string[:,0],"-15")
np.unique(loan_data_string[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [584]:
month=np.array(["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug",
                "Sep","Oct","Nov","Dec"])

In [585]:
for i in range(13):
               loan_data_string[:,0]=np.where(loan_data_string[:,0]==month[i],
                                              i,
                                              loan_data_string[:,0])

In [586]:
 np.unique(loan_data_string[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

LOAN STATUS

In [587]:
np.unique(loan_data_string[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [588]:
status_bad=np.array(["","Charged Off","Default",
                     "Late (16-30 days)","Late (120days)"])

In [589]:
loan_data_string[:,1]=np.where(np.isin(loan_data_string[:,1], status_bad),
                               0,
                               1)

In [590]:
np.unique(loan_data_string[:,1])

array(['0', '1'], dtype='<U69')

In [591]:
header_string

array(['issue-date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

TERM

In [592]:
np.unique(loan_data_string[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [593]:
loan_data_string[:,2]=np.chararray.strip(loan_data_string[:,2]," months")
np.unique(loan_data_string[:,2])

array(['', '36', '60'], dtype='<U69')

In [594]:
header_string[2]="term-months"

In [595]:
loan_data_string[:,2]=np.where(loan_data_string[:,2]=="","60 ",
                               loan_data_string[:,2])

In [596]:
np.unique(loan_data_string[:,2])

array(['36', '60', '60 '], dtype='<U69')

GRADE AND SUBGRADE

In [597]:
header_string

array(['issue-date', 'loan_status', 'term-months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [598]:
np.unique(loan_data_string[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [599]:
np.unique(loan_data_string[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [600]:
for i in np.unique(loan_data_string[:,3])[1:]:
    loan_data_string[:,4] = np.where((loan_data_string[:,4] == '') & (loan_data_string[:,3] == i),
                                      i + '5',
                                      loan_data_string[:,4])

In [601]:
for i in np.unique(loan_data_string[:,3])[1:]:
    loan_data_string[:,4] = np.where((loan_data_string[:,4] == '') ,
                                      "H1",
                                      loan_data_string[:,4])

In [602]:
np.unique(loan_data_string[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

REMOVING ROWS

In [603]:
loan_data_string=np.delete(loan_data_string,3 ,axis=1)
(loan_data_string[:,3])

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [604]:
header_string=np.delete(header_string,3)
header_string[3]

'sub_grade'

CONVERTING SUBGRADES

In [605]:
keys = list(np.unique(loan_data_string[:,3]))                         
values = list(range(1, np.unique(loan_data_string[:,3]).shape[0] + 1)) 
dict_sub_grade = dict(zip(keys, values))

In [606]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [607]:
for i in np.unique(loan_data_string[:,3]):
        loan_data_string[:,3] = np.where(loan_data_string[:,3] == i, 
                                          dict_sub_grade[i],
                                          loan_data_string[:,3])

In [608]:
np.unique(loan_data_string[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

VERIFICATION STATUS

In [609]:
header_string

array(['issue-date', 'loan_status', 'term-months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [610]:
np.unique(loan_data_string[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [611]:
loan_data_string[:,4]=np.where((loan_data_string[:,4]=="") | 
                               (loan_data_string[:,4]=="Not Verified"),
                              0,1)

In [612]:
np.unique(loan_data_string[:,4])

array(['0', '1'], dtype='<U69')

URL

In [613]:
loan_data_string[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [614]:
loan_data_string[:,5]=np.chararray.strip(
    loan_data_string[:,5],
    "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [615]:
loan_data_string[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [616]:
loan_data_string=np.delete(loan_data_string, 5, axis=1)
header_string=np.delete(header_string, 5)

In [617]:
loan_data_string[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [618]:
header_string

array(['issue-date', 'loan_status', 'term-months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

STATE ADDRESS

In [619]:
header_string

array(['issue-date', 'loan_status', 'term-months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [620]:
state_name,state_count=np.unique(loan_data_string[:,5],return_counts=True)

In [621]:
state_count_sorted=np.argsort(-state_count)

In [622]:
state_count_sorted

array([ 5, 33, 42, 10,  0, 13, 30, 11, 37, 34, 21, 26, 44, 19,  4, 46, 18,  6, 23, 22, 14, 47,  7,
       41, 32,  2, 17, 36, 39, 16, 15, 35, 43,  3, 24, 29, 31, 48, 12, 38, 25,  9,  8, 49,  1, 28,
       40, 45, 27, 20], dtype=int64)

In [623]:
state_name[state_count_sorted],state_count[state_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [624]:
loan_data_string[:,5]=np.where(loan_data_string[:,5]=="",0,
                              loan_data_string[:,5])


In [625]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [626]:
loan_data_string[:,5]=np.where(np.isin(loan_data_string[:,5],states_west),1,
                                   loan_data_string[:,5],)
loan_data_string[:,5]=np.where(np.isin(loan_data_string[:,5],states_south),2,
                                   loan_data_string[:,5],)
loan_data_string[:,5]=np.where(np.isin(loan_data_string[:,5],states_midwest),3,
                                   loan_data_string[:,5],)
loan_data_string[:,5]=np.where(np.isin(loan_data_string[:,5],states_east),4,
                                   loan_data_string[:,5],)

In [627]:
np.unique(loan_data_string[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [628]:
loan_data_string.astype(int)

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

MANIPULATING NUMERIC COLUMNS

In [629]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [630]:
loan_data_numeric=np.genfromtxt("loan-data.csv",delimiter=";",autostrip=True 
                               ,usecols=column_numeric, skip_header=1,
                                filling_values=temporary_fill)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [631]:
np.isnan(loan_data_numeric).sum()

0

In [632]:
np.isin(loan_data_numeric[:,0],temporary_fill).sum()

0

In [633]:
temporary_stat=np.array([np.nanmin(run_data_np,axis=0),temporary_mean,
                         np.nanmax(run_data_np,axis=0)])
temporary_stat

<ipython-input-633-530e986a876c>:1: RuntimeWarning: All-NaN slice encountered
  temporary_stat=np.array([np.nanmin(run_data_np,axis=0),temporary_mean,
<ipython-input-633-530e986a876c>:2: RuntimeWarning: All-NaN slice encountered
  np.nanmax(run_data_np,axis=0)])


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [634]:
temporary_stat[:,column_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [635]:
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

FUNDED AMOUNT

In [636]:
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temporary_fill, 
                                  temporary_stat[0, column_numeric[2]],
                                  loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

OTHER NUMERIC COLUMNS

In [637]:
for i in [1,3,4,5]:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] == temporary_fill, 
                                  temporary_stat[2, column_numeric[i]],
                                  loan_data_numeric[:,i])
 

THE EXCHANGE RATE

In [638]:
eur_usd=np.genfromtxt("EUR-USD.csv",delimiter=",",
                      autostrip=True,skip_header=1,usecols=3)

In [639]:
eur_usd

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [640]:
loan_data_string=loan_data_string.astype(dtype=int)
loan_data_string

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [641]:
exchange_rate=loan_data_string[:,0]
for i in range(1,13):
    exchange_rate=np.where(exchange_rate == i,
                             eur_usd[i-1],
                             exchange_rate) 
exchange_rate = np.where(exchange_rate == 0,
                             np.mean(eur_usd),
                             exchange_rate)
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [642]:
exchange_rate=exchange_rate.reshape(10000,1)

In [643]:
loan_data_numeric=np.hstack((loan_data_numeric,exchange_rate))
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [644]:
header_numeric=np.concatenate((header_numeric,np.array(["exchange-rate"])))

In [645]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange-rate'],
      dtype='<U19')

FROM USD TO EUR

In [646]:
column_dollar=np.array([1,2,4,5])

In [647]:
loan_data_numeric[:,column_dollar]

array([[35000.  , 35000.  ,  1184.86,  9452.96],
       [30000.  , 30000.  ,   938.57,  4679.7 ],
       [15000.  , 15000.  ,   494.86,  1969.83],
       ...,
       [10000.  , 10000.  ,  1372.97,  2185.64],
       [35000.  , 10000.  ,   354.3 ,  3199.4 ],
       [10000.  , 10000.  ,   309.97,   301.9 ]])

In [648]:
for i in column_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric,
                                   np.reshape(loan_data_numeric[:,i] / loan_data_numeric[:,6],
                                              (10000,1))))
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [649]:
header_additional = np.array([column_name + '_EUR' for column_name 
                 in header_numeric[column_dollar]])
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [650]:
header_numeric=np.concatenate((header_numeric,header_additional))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange-rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [651]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]
header_numeric=header_numeric[columns_index_order]
header_numeric

array(['id', 'loan_amnt', 'loan_amnt_EUR', 'funded_amnt', 'funded_amnt_EUR', 'int_rate',
       'installment', 'installment_EUR', 'total_pymnt', 'total_pymnt_EUR', 'exchange-rate'],
      dtype='<U19')

In [652]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [653]:
loan_data_numeric=loan_data_numeric[:,columns_index_order]

In [654]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

INTEREST RATE

In [655]:
header_numeric

array(['id', 'loan_amnt', 'loan_amnt_EUR', 'funded_amnt', 'funded_amnt_EUR', 'int_rate',
       'installment', 'installment_EUR', 'total_pymnt', 'total_pymnt_EUR', 'exchange-rate'],
      dtype='<U19')

In [656]:
loan_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [657]:
loan_data_numeric[:,5]=loan_data_numeric[:,5]/100
loan_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

CREATING THE COMPLETE DATASET

In [658]:
loan_data_numeric.shape

(10000, 11)

In [659]:
loan_data_string.shape

(10000, 6)

In [660]:
loan_data=np.hstack((loan_data_numeric,loan_data_string))

In [661]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [662]:
np.isnan(loan_data).sum()

0

In [663]:
header_full=np.concatenate((header_numeric,header_string))

In [664]:
header_full

array(['id', 'loan_amnt', 'loan_amnt_EUR', 'funded_amnt', 'funded_amnt_EUR', 'int_rate',
       'installment', 'installment_EUR', 'total_pymnt', 'total_pymnt_EUR', 'exchange-rate',
       'issue-date', 'loan_status', 'term-months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [665]:
loan_data=loan_data[np.argsort(loan_data[:,0])]

In [666]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [667]:
loan_data=np.vstack((header_full,loan_data))
loan_data

array([['id', 'loan_amnt', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status', 'addr_state'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [668]:
np.savetxt("loan_data_preprocessed.csv",loan_data,fmt="%s",delimiter=",")